#!/bin/bash
#SBATCH -A C3SE2026-1-12
#SBATCH -C ZEN4
#SBATCH --exclusive
#SBATCH -p vera
#SBATCH -J HeCBench
#SBATCH -N 1
#SBATCH -t 24:00:00
#SBATCH -e hecbench_err_amd

######################-------------------######################

cd /cephyr/users/antonkra/Vera/HeCBench

IMG=/cephyr/users/antonkra/Vera/HeCBench/rocky-acpp.sif

# export ACPP_VISIBILITY_MASK=ocl
export ACPP_VISIBILITY_MASK=omp

apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src
