#!/bin/bash
#SBATCH -A C3SE2026-1-12
#SBATCH -C ICELAKE
#SBATCH --exclusive
#SBATCH -p vera
#SBATCH -J HeCBench
#SBATCH -N 1
#SBATCH -t 24:00:00
#SBATCH -e hecbench_err_amd

######################-------------------######################

cd /cephyr/users/gustavva/Vera/HeCBench

IMG=/cephyr/users/gustavva/Vera/HeCBench/acpp.sif

export ACPP_VISIBILITY_MASK=omp

apptainer exec $IMG python3 clean_all.py --sycl-root=src

apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src --pattern=gabor-sycl --results-dir=omp_results_icelake_warmup --extra-runs=1
apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src --pattern=gabor-sycl --results-dir=omp_results_icelake_likwid_sp --likwid=64 --likwid-precision=sp
apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src --pattern=gabor-sycl --results-dir=omp_results_icelake_likwid_dp --likwid=64 --likwid-precision=dp

export ACPP_VISIBILITY_MASK=ocl

apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src --pattern=gabor-sycl --results-dir=ocl_results_icelake_warmup --extra-runs=1
apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src --pattern=gabor-sycl --results-dir=ocl_results_icelake_likwid_sp --likwid=64 --likwid-precision=sp
apptainer exec $IMG python3 run-hecbench-sycl.py --sycl-root=src --pattern=gabor-sycl --results-dir=ocl_results_icelake_likwid_dp --likwid=64 --likwid-precision=dp
